<?php

namespace Test\TopicBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getCommentsForTopic($topicId)
    {
        $qb = $this->createQueryBuilder('c')
                   ->select('c')
                   ->where('c.topic = :topic_id')
                   ->addOrderBy('c.topic')
                   ->setParameter('topic_id', $topicId);

        return $qb->getQuery()
                  ->getResult();
    }
}
